### ISSUE TITLE
Dataset versioning

### ISSUE THREAD

**Issue by 5c0r** [peochot/Innovation#24]
Usage of redux-persist to save redux state

Versioning dataset

**Comment by 5c0r** [comment]
@peochot : TODO : Add lastUpdated field to list response to define last updated dataset 
- Suggestion : Maybe using creationDate of last crawled job ?

**Comment by peochot** [comment]
Added last_modified filed . Pls clear job data and run crawler

**Comment by 5c0r** [comment]
Discard this feature since because of over-engineered
