### ISSUE TITLE
Apply route and component

### ISSUE THREAD

**Issue by peochot** [peochot/Innovation#4]
Read http://redux-form.com/6.1.1/ 
- Make a form with

-A select to choose cover letter template =>Get the template from store =>Display letter in text area =>User edit text area
-A radio button to choose use uploaded resumes or upload new file

-An input field to upload file if upload new file is selected

-A select to choose which uploaded resume (get resume from store) if use uploaded is selected

**Comment by 5c0r** [comment]
Done
